/*
 * msg_types.h
 *
 *  Created on: Feb 16, 2016
 *      Author: bush
 */

#ifndef PROTOCOL_INC_MSG_TYPES_H_
#define PROTOCOL_INC_MSG_TYPES_H_


typedef enum {
	TYPE_KEYS = 0,
	TYPE_MASK_INPUTS,
	TYPE_MASK_OUTPUT,
	TYPE_PRF_OUTPUTS,
	TYPE_GARBLED_CIRCUIT,
	TYPE_EXTERNAL_VALUES,
	TYPE_ALL_EXTERNAL_VALUES,
	TYPE_KEY_PER_IN_WIRE,
	TYPE_ALL_KEYS_PER_IN_WIRE,
	TYPE_LAUNCH_ONLINE,
	TYPE_RECEIVED_GC,

	TYPE_CHECKSUM,
	TYPE_MAX
} MSG_TYPE;


#endif /* PROTOCOL_INC_MSG_TYPES_H_ */
